# Generated by Django 3.2 on 2021-05-08 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='insurancetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Insurancerecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('insurance_id', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=35)),
                ('mobile', models.IntegerField(max_length=10)),
                ('insurancename', models.CharField(max_length=50)),
                ('insurancetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_register.insurancetype')),
            ],
        ),
    ]
